version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fracttal_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasklist_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: fracttal_api
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # Evita que el node_modules local sobreescriba el del contenedor
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tasklist_db?schema=public
      - PORT=3001

volumes:
  postgres_data:
