export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SESSION_ERROR = 'SESSION_ERROR';

export const USER_AUTHENTICATE = 'USER_AUTHENTICATE';
export const LOGOUT = 'LOGOUT';

export const REMOVE_ALERTS = 'REMOVE_ALERTS';
